---
collections:
  - name: community.general
  - name: ansible.posix
  - name: kubernetes.core
  - name: community.crypto
  - name: kenmoini.redfish
  - name: kenmoini.phpipam
  #- name: kenmoini.powerdns_admin